title: stimator
author: António Ferreira
copyright: "2022"
logo: newlogo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: stimator.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

repository:
  url: https://github.com/aeferreira/stimator

html:
  use_issues_button: false
  use_repository_button: true
  use_launch_button: false

sphinx:
  config:
    #language: "pt_PT"
    nb_merge_streams: true
    html_theme_options:
      launch_buttons: {}