title: stimator
author: António Ferreira
copyright: "2023 by António Ferreira"
logo: newlogo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: stimator.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

repository:
  url: https://github.com/aeferreira/stimator

html:
  use_issues_button: false
  use_repository_button: true
  use_launch_button: false

sphinx:
  recursive_update: true
  config:
    project: "S-timator"
    #language: "pt_PT"
    html_theme: pydata_sphinx_theme
    nb_merge_streams: true
    html_theme_options:
      github_url: https://github.com/aeferreira/stimator
      secondary_sidebar_items:
        - page-toc
